fast forward to git snapshot by hand

diff --git a/Makefile.am b/Makefile.am
--- a/Makefile.am
+++ b/Makefile.am
@@ -9,7 +9,7 @@
 #  - libs/* are needed by modules
 BASE_SUBDIRS = po src bin modules share doc test
 EXTRA_SUBDIRS = m4 extras/package/ipkg \
-	libs/loader libs/srtp \
+	libs/loader libs/srtp libs/unzip \
 	projects/mozilla projects/activex
 DIST_SUBDIRS = $(BASE_SUBDIRS) $(EXTRA_SUBDIRS)
 
@@ -19,6 +19,11 @@ SUBDIRS += libs/loader
 endif
 if HAVE_LIBGCRYPT
 SUBDIRS += libs/srtp
+endif
+if HAVE_ZLIB
+if !HAVE_MINIZIP
+SUBDIRS += libs/unzip
+endif
 endif
 if BUILD_VLC
 SUBDIRS += bin
@@ -41,7 +46,6 @@ EXTRA_DIST = \
 	extras/package/macosx/README.MacOSX.rtf \
 	vlc-config.in.in \
 	extras/package/rpm/vlc.fedora.spec \
-	extras/package/rpm/vlc.mandriva.spec \
 	extras/package/rpm/vlc.altlinux.spec \
 	extras/package/win32/vlc.win32.nsi.in \
 	extras/package/win32/languages/declaration.nsh \
@@ -360,7 +364,7 @@ endif
 # Building aliases
 ###############################################################################
 
-ALL_ALIASES = cvlc rvlc svlc wxvlc qvlc nvlc
+ALL_ALIASES = cvlc rvlc svlc wxvlc qvlc nvlc mvlc
 bin_SCRIPTS = $(ALIASES)
 CLEANFILES += $(ALIASES) $(noinst_SCRIPTS)
 EXTRA_SCRIPTS = $(ALL_ALIASES)
@@ -369,23 +373,26 @@ dist_noinst_SCRIPTS += make-alias
 
 MKALIAS = bindir="$(bindir)" transform="$(transform)" program_prefix="$(program_prefix)" program_suffix="$(program_suffix)" $(top_srcdir)/make-alias $@
 
-cvlc: make-alias
+cvlc: make-alias Makefile
 	$(MKALIAS) dummy
 
-rvlc: make-alias
+rvlc: make-alias Makefile
 	$(MKALIAS) rc
 
-svlc: make-alias
+svlc: make-alias Makefile
 	$(MKALIAS) skins2
 
-wxvlc: make-alias
+wxvlc: make-alias Makefile
 	$(MKALIAS) wx
 
-qvlc: make-alias
+qvlc: make-alias Makefile
 	$(MKALIAS) qt4
 
-nvlc: make-alias
+nvlc: make-alias Makefile
 	$(MKALIAS) ncurses
+
+mvlc: make-alias Makefile
+	$(MKALIAS) maemo
 
 if BUILD_VLC
 noinst_SCRIPTS += vlc$(EXEEXT)
@@ -394,7 +401,7 @@ endif
 vlc$(EXEEXT): Makefile.am
 	rm -f -- vlc vlc.tmp
 	echo '#! /bin/sh' > vlc.tmp
-	echo 'exec "$$(dirname "$$0")/bin/vlc$(EXEEXT)" "--plugin-path=$$(dirname "$$0")/modules" "$$@"' >> vlc.tmp
+	echo 'exec "$$(dirname "$$0")/bin/vlc-static$(EXEEXT)" "--plugin-path=$$(dirname "$$0")/modules" "$$@"' >> vlc.tmp
 	chmod +x vlc.tmp
 	mv -f -- vlc.tmp vlc
 
@@ -415,7 +422,7 @@ VLC-release.app: vlc
 	for i in vlc.xcodeproj Resources README.MacOSX.rtf ; do \
 	  cp -R $(srcdir)/extras/package/macosx/$$i $(top_builddir)/tmp/extras/package/macosx/; \
 	done
-	REVISION=`git describe` && \
+	REVISION=`git describe --always` && \
 	cat $(top_builddir)/extras/package/macosx/Info.plist | \
 	sed "s/#REVISION#/$$REVISION/g" > $(top_builddir)/tmp/extras/package/macosx/Info.plist
 	cp -R $(top_builddir)/extras/package/macosx/Resources $(top_builddir)/tmp/extras/package/macosx/
@@ -582,7 +589,7 @@ VLC.app: vlc $(top_builddir)/src/.libs/libvlccore.dylib $(top_builddir)/src/.lib
 	for i in vlc.xcodeproj Resources README.MacOSX.rtf; do \
 	  cp -R $(srcdir)/extras/package/macosx/$$i $(top_builddir)/tmp/extras/package/macosx/; \
 	done
-	REVISION=`git describe` && \
+	REVISION=`git describe --always` && \
 	cat $(top_builddir)/extras/package/macosx/Info.plist | \
 	sed "s/#REVISION#/$$REVISION/g" > $(top_builddir)/tmp/extras/package/macosx/Info.plist
 	cp -R $(top_builddir)/extras/package/macosx/Resources $(top_builddir)/tmp/extras/package/macosx/
@@ -674,7 +681,13 @@ VLC.app: vlc $(top_builddir)/src/.libs/libvlccore.dylib $(top_builddir)/src/.lib
 # the same setup as the maintaner(s).
 #
 
+############################################################################
+## Win                                                                    ##
+############################################################################
 win32_destdir=$(top_builddir)/vlc-$(VERSION)
+win32_debugdir=$(top_builddir)/symbols-$(VERSION)
+npvlc=vlc-$(VERSION)/mozilla/npvlc$(LIBEXT)
+axvlc=vlc-$(VERSION)/activex/axvlc$(LIBEXT)
 win32_lua_destdir=$(win32_destdir)/lua
 win32_http_destdir=$(win32_destdir)/http
 
@@ -701,10 +714,10 @@ package-win-common:
 	  do sed 's/@/_AT_/' < "$(srcdir)/$$file" > "$(win32_destdir)/$${file}.txt" ; done;
 	for file in NEWS COPYING README; \
 	  do cp "$(srcdir)/$$file" "$(win32_destdir)/$${file}.txt"; done
-	unix2dos "$(win32_destdir)/"*.txt
+	unix2dos "$(win32_destdir)/"*.txt || echo "WARNING: this shouldn't happen"
 
 # Necessary icons
-	cp $(srcdir)/share/vlc48x48.ico $(win32_destdir)/
+	cp $(srcdir)/share/vlc.ico $(win32_destdir)/
 
 # Copy the locales
 	mkdir -p $(win32_destdir)/locale
@@ -755,7 +768,7 @@ package-win32-base-debug: package-win-common
 	  fi ; done
 
 # Contrib *.dll's
-	cp $(srcdir)/extras/contrib/lib/*.dll "vlc-$(VERSION)/" || true 
+	cp $(srcdir)/extras/contrib/lib/*.dll "vlc-$(VERSION)/" || true
 
 # Copy the lua scripts (HTTP)
 if BUILD_LUA
@@ -853,20 +866,18 @@ if BUILD_SKINS
 	for i in $(srcdir)/share/skins2/fonts/*.*; do \
 	  cp -- "$$i" $(win32_destdir)/skins/fonts/ || true ; \
 	done
-	for i in $(srcdir)/share/skins2/*.*; do \
+	for i in $(top_builddir)/share/skins2/*.*; do \
 	  cp -- "$$i" $(win32_destdir)/skins/ || true ; \
 	done
-	cp -v share/skins2/default.vlt $(win32_destdir)/skins/ || true ;
-
 endif
 
 if BUILD_OSDMENU
 #OSD Menu
 	mkdir -p "$(win32_destdir)/osdmenu"
 	cp $(srcdir)/share/osdmenu/*.* "$(win32_destdir)/osdmenu"
-	for dir in dvd dvd/selected dvd/unselect dvd/selection dvd/volume default default/selected default/selection default/volume minimal;do \
+	for dir in default default/selected default/selection default/volume ;do \
 		mkdir -p "$(win32_destdir)/osdmenu/$$dir"; \
-		for file in $(srcdir)/share/osdmenu/$${dir}/*.png ;do \
+		for file in $(srcdir)/share/osdmenu/$${dir}/*.png;do \
 			 cp -- "$$file" "$(win32_destdir)/osdmenu/$$dir"; \
 		done; \
 	done
@@ -890,19 +901,42 @@ endif
 
 #strip exe and main dll
 package-win-common-strip: package-win32-base-debug
+	@if test -e "$(win32_debugdir)"; then \
+	  echo "Error: please remove $(win32_debugdir), it is in the way"; \
+	  false; \
+	else \
+	  echo "OK."; mkdir -p "$(win32_debugdir)"; \
+	fi
 	for i in "" vlc-$(VERSION)/*$(LIBEXT) ; \
-	  do if test -n "$$i" ; then $(STRIP) "$$i" ; fi; done
+      do if test -n "$$i" ; then \
+      $(OBJCOPY) --only-keep-debug "$$i" "$$i.dbg"; \
+      $(OBJCOPY) --strip-debug "$$i" ; \
+      $(OBJCOPY) --add-gnu-debuglink="$$i.dbg" "$$i" ; \
+	  mv "$$i.dbg" "$(win32_debugdir)"; \
+    fi; done
+
 if BUILD_MOZILLA
-	$(STRIP) "vlc-$(VERSION)/mozilla/npvlc$(LIBEXT)"
+	$(OBJCOPY) --only-keep-debug "$(npvlc)" "$(npvlc).dbg"
+	$(OBJCOPY) --strip-debug "$(npvlc)"
+	$(OBJCOPY) --add-gnu-debuglink="$(npvlc).dbg" "$(npvlc)"
+	mv "$(npvlc).dbg" "$(win32_debugdir)"
 endif
 if BUILD_ACTIVEX
-	$(STRIP) "vlc-$(VERSION)/activex/axvlc$(LIBEXT)"
+	$(OBJCOPY) --only-keep-debug "$(axvlc)" "$(axvlc).dbg"
+	$(OBJCOPY) --strip-debug "$(axvlc)"
+	$(OBJCOPY) --add-gnu-debuglink="$(axvlc).dbg" "$(axvlc)"
+	mv "$(axvlc).dbg" "$(win32_debugdir)"
 endif
 
 #strip all plugins dll
 package-win32-base: package-win-common-strip
 	for i in "" $(win32_destdir)/plugins/*$(LIBEXT) ; \
-	  do if test -n "$$i" ; then $(STRIP) "$$i" ; fi ; done
+	  do if test -n "$$i" ; then \
+	  $(OBJCOPY) --only-keep-debug "$$i" "$$i.dbg"; \
+	  $(OBJCOPY) --strip-debug "$$i" ; \
+	  $(OBJCOPY) --add-gnu-debuglink="$$i.dbg" "$$i" ; \
+	  mv "$$i.dbg" "$(win32_debugdir)"; \
+	fi ; done
 
 package-win32-base-exe: package-win32-base
 # Create package
@@ -925,9 +959,18 @@ package-win32-base-zip: package-win32-base
 	rm -f -- vlc-$(VERSION)-win32.zip
 	zip -r -9 vlc-$(VERSION)-win32.zip vlc-$(VERSION)
 
+package-win32-base-debug-zip: package-win32-base-debug
+# Create package
+	rm -f -- vlc-$(VERSION)-win32-debug.zip
+	zip -r -9 vlc-$(VERSION)-win32-debug.zip vlc-$(VERSION)
+
 package-win32-base-7zip: package-win32-base
 # Create package 
 	7z a -t7z -m0=lzma -mx=9 -mfb=64 -md=32m -ms=on vlc-$(VERSION)-win32.7z vlc-$(VERSION)
+
+package-win32-base-debug-7zip: package-win32-base-debug
+# Create package
+	7z a -t7z -m0=lzma -mx=9 -mfb=64 -md=32m -ms=on vlc-$(VERSION)-win32-debug.7z vlc-$(VERSION)
 
 package-win32-exe: package-win32-base package-win32-base-exe
 # Clean up
@@ -937,13 +980,25 @@ package-win32-zip: package-win32-base-zip
 # Clean up
 	rm -Rf $(win32_destdir)
 
+package-win32-debug-zip: package-win32-base-debug-zip
+# Clean up
+	rm -Rf $(win32_destdir)
+
 package-win32-7zip: package-win32-base-7zip
+# Clean up
+	rm -Rf $(win32_destdir)
+
+package-win32-debug-7zip: package-win32-base-debug-7zip
 # Clean up
 	rm -Rf $(win32_destdir)
 
 package-win32-no-clean: package-win32-base-zip package-win32-base-7zip package-win32-base-exe 
 
 package-win32: package-win32-no-clean
+# Clean up
+	rm -Rf $(win32_destdir)
+
+package-win32-debug: package-win32-base-debug-zip package-win32-base-debug-7zip
 # Clean up
 	rm -Rf $(win32_destdir)
 
@@ -958,6 +1013,9 @@ package-wince: package-wince-base  package-wince-base-zip
 	rm -Rf $(win32_destdir)
 
 
+#####################################################################
+##   BeOS                                                          ##
+#####################################################################
 package-beos:
 # Check that tmp isn't in the way
 	@if test -e $(srcdir)/tmp; then \
@@ -993,6 +1051,9 @@ package-beos:
 # Clean up
 	rm -Rf $(srcdir)/tmp
 
+#########################################################################
+## MacOS X                                                             ##
+#########################################################################
 package-macosx: VLC-release.app ChangeLog
 # Check that the temporary location isn't in the way
 	@if test -e "$(top_builddir)/vlc-$(VERSION)/"; then \
diff --git a/extras/contrib/bootstrap b/extras/contrib/bootstrap
--- a/extras/contrib/bootstrap
+++ b/extras/contrib/bootstrap
@@ -2,12 +2,12 @@
 # ***************************************************************************
 # bootstrap : Set up config.mak
 # ***************************************************************************
-# Copyright (C) 2003-2007 the VideoLAN team
+# Copyright (C) 2003-2009 the VideoLAN team
 # $Id$
 #
 # Authors: Christophe Massiot <massiot@via.ecp.fr>
 #          Derk-Jan Hartman <hartman at videolan dot org>
-#          Felix Kühne <fkuehne@users.sourceforge.net>
+#          Felix Paul Kühne <fkuehne at videolan dot org>
 #
 # This program is free software; you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -70,11 +70,28 @@ if test "$HOST" != "$BUILD"; then
     STRIP="${HOST}-strip"
 fi
 
+case $HOST in
+    *powerpc*|*ppc*)
+         echo "ARCH=ppc" >> config.mak
+     ;;
+    *darwin10*)
+         echo "ARCH=x86_64" >> config.mak
+     ;;
+    *86*)
+          echo "ARCH=i386" >> config.mak
+     ;;
+esac
+
 # Check the HAVE_{OS}
 case $HOST in
     *darwin*)
         echo "HAVE_DARWIN_OS = 1" >> config.mak
         echo "HAVE_BSD = 1" >> config.mak
+        if test $CONTRIBS_CC_LLVM; then
+            echo "DARWIN_COMPILER = LLVMGCC" >> config.mak
+        else
+            echo "DARWIN_COMPILER = GCC" >> config.mak
+        fi
     ;;
     *linux*)
         echo "HAVE_LINUX = 1" >> config.mak
@@ -127,15 +144,30 @@ case $HOST in
     ;;
     powerpc-apple-darwin9)
 # Mac OS X 10.5 with Xcode 3, specific rules apply
-        SDK_TARGET=10.4
+        if test -z "$CONTRIBS_CC_LLVM"; then
+            SDK_TARGET=10.4
+        else
+            SDK_TARGET=10.5
+        fi
         echo "SDK_TARGET = ${SDK_TARGET}" >> config.mak
         echo "ENVP = MACOSX_DEPLOYMENT_TARGET=${SDK_TARGET}" >> config.mak
-        echo "MACOSX_SDK = /Developer/SDKs/MacOSX10.4u.sdk" >> config.mak
+        if test -z "$CONTRIBS_CC_LLVM"; then
+            echo "MACOSX_SDK = /Developer/SDKs/MacOSX10.4u.sdk" >> config.mak
+        else
+            echo "MACOSX_SDK = /Developer/SDKs/MacOSX10.5.sdk" >> config.mak
+        fi
         echo "HAVE_DARWIN_9 = 1" >> config.mak
+        HAVE_DARWIN_9=1
         CFLAGS_TUNING=" -arch ppc -mtune=G4"
-        EXTRA_CFLAGS=" -D\${ENVP} -mmacosx-version-min=\${SDK_TARGET}"
-        CC="gcc -isysroot \${MACOSX_SDK}"
-        CXX="g++ -isysroot \${MACOSX_SDK}"
+        EXTRA_CFLAGS=" -D\${ENVP} -isysroot \${MACOSX_SDK} -mmacosx-version-min=\${SDK_TARGET}"
+        EXTRA_LDFLAGS=" -isysroot \${MACOSX_SDK} -Wl,-syslibroot,\${MACOSX_SDK}"
+        if test -z "$CONTRIBS_CC_LLVM"; then
+            CC="gcc"
+            CXX="g++"
+        else
+            CC="/Developer/usr/llvm-gcc-4.2/bin/llvm-gcc-4.2"
+            CXX="/Developer/usr/llvm-gcc-4.2/bin/llvm-g++-4.2"
+        fi
         LD="ld -arch ppc -syslibroot \${MACOSX_SDK}"
         echo "PATH = /bin:/usr/bin:/usr/local/bin:" >> config.mak
         cat src/Distributions/darwin.mak >> distro.mak
@@ -147,19 +179,36 @@ case $HOST in
         fi
     ;;
     i686-apple-darwin9)
-        SDK_TARGET=10.4
+        if test -z "$CONTRIBS_CC_LLVM"; then
+            SDK_TARGET=10.4
+        else
+            SDK_TARGET=10.5
+        fi
         MIN_LD_VERSION_WITH_TEXT_RELOCATION=81
         echo "SDK_TARGET = ${SDK_TARGET}" >> config.mak
         echo "HAVE_DARWIN_OS_ON_INTEL = 1" >> config.mak
         echo "HAVE_DARWIN_9 = 1" >> config.mak
+        HAVE_DARWIN_9=1
         if test `ld -v 2> /dev/stdout | sed -E 's/.*ld64-([0-9]+).*/\1/'` -lt ${MIN_LD_VERSION_WITH_TEXT_RELOCATION}; then
-            echo "NO_TEXT_RELOCATION = 1" >> config.mak
+            echo "ERROR: Your ld version is unable to compile VLC.\nUpdate to Xcode 3.1 or higher." >&2
+            exit 1
         fi
         echo "ENVP = MACOSX_DEPLOYMENT_TARGET=${SDK_TARGET}" >> config.mak
-        echo "MACOSX_SDK = /Developer/SDKs/MacOSX10.4u.sdk" >> config.mak
+        if test -z "$CONTRIBS_CC_LLVM"; then
+            echo "MACOSX_SDK = /Developer/SDKs/MacOSX10.4u.sdk" >> config.mak
+        else
+            echo "MACOSX_SDK = /Developer/SDKs/MacOSX10.5.sdk" >> config.mak
+        fi
         CFLAGS_TUNING=" -march=pentium-m -mtune=prescott"
         EXTRA_CFLAGS=" -D\${ENVP} -isysroot \${MACOSX_SDK} -mmacosx-version-min=\${SDK_TARGET}"
         EXTRA_LDFLAGS=" -isysroot \${MACOSX_SDK} -Wl,-syslibroot,\${MACOSX_SDK}"
+        if test -z "$CONTRIBS_CC_LLVM"; then
+            CC="gcc"
+            CXX="g++"
+        else
+            CC="/Developer/usr/llvm-gcc-4.2/bin/i686-apple-darwin9-llvm-gcc-4.2"
+            CXX="/Developer/usr/llvm-gcc-4.2/bin/i686-apple-darwin9-llvm-g++-4.2"
+        fi
         echo "PATH = /bin:/usr/bin:/usr/local/bin" >> config.mak
         cat src/Distributions/darwin.mak >> distro.mak
         if test -e /Developer/SDKs; then
@@ -169,18 +218,21 @@ case $HOST in
             exit 1
         fi
     ;;
-    i686-apple-darwin10d1)
-        SDK_TARGET=10.6
+    *-apple-darwin10)
+        SDK_TARGET=10.5
         echo "SDK_TARGET = ${SDK_TARGET}" >> config.mak
         echo "HAVE_DARWIN_OS_ON_INTEL = 1" >> config.mak
         echo "HAVE_DARWIN_9 = 1" >> config.mak
         echo "HAVE_DARWIN_10 = 1" >> config.mak
+        HAVE_DARWIN_10=1
         echo "ENVP = MACOSX_DEPLOYMENT_TARGET=${SDK_TARGET}" >> config.mak
-        echo "MACOSX_SDK = /Developer/SDKs/MacOSX10.6.sdk" >> config.mak
-        CFLAGS_TUNING=" -march=pentium-m -mtune=prescott"
+        echo "MACOSX_SDK = /Developer/SDKs/MacOSX${SDK_TARGET}.sdk" >> config.mak
+        CFLAGS_TUNING=" -march=core2"
         EXTRA_CFLAGS=" -D\${ENVP} -isysroot \${MACOSX_SDK} -mmacosx-version-min=\${SDK_TARGET}"
         EXTRA_LDFLAGS=" -isysroot \${MACOSX_SDK} -Wl,-syslibroot,\${MACOSX_SDK}"
         echo "PATH = /bin:/usr/bin:/usr/local/bin" >> config.mak
+        CC="gcc"
+        CXX="g++"
         cat src/Distributions/darwin.mak >> distro.mak
         if test -e /Developer/SDKs; then
             echo "SDKs found. Everything is fine." >&2
@@ -313,10 +365,37 @@ fi
 if test -z "$CONTRIBS_RELEASE"; then
     set +x
     echo
-    echo "***********************************************************"
-    echo "* If you are building contribs for a release build of VLC *"
-    echo "* Please run CONTRIBS_RELEASE=sexy ./bootstrap            *"
-    echo "***********************************************************"
+    echo "*****************************************************************"
+    echo "* If you are building contribs for a release build of VLC       *"
+    echo "* Please run CONTRIBS_RELEASE=sexy ./bootstrap                  *"
+    echo "*                                                               *"
+    echo "* Ignore this message if you don't compile the 3rd party        *"
+    echo "* libraries your own aka by just running 'make' next.           *"
+    echo "*****************************************************************"
 else
     echo "EXTRA_CFLAGS += -DNDEBUG" >> config.mak
+    set -x
+fi
+
+if test $HAVE_DARWIN_9; then
+if test -z "$CONTRIBS_CC_LLVM"; then
+    set +x
+    echo
+    echo "*****************************************************************"
+    echo "* In case that you target Mac OS X 10.5 or later only,          *"
+    echo "* we recommend to use llvm-gcc-4.2 for compilation.             *"
+    echo "* Please run CONTRIBS_CC_LLVM=yes ./bootstrap to do so.         *"
+    echo "*****************************************************************"
+    set -x
+fi
+fi
+
+if test $HAVE_DARWIN_10; then
+    set +x
+    echo
+    echo "*****************************************************************"
+    echo "* You are running Darwin 10.                                    *"
+    echo "* For testing purposes, VLC will be compiled in 64bit mode.     *"
+    echo "*****************************************************************"
+    set -x
 fi
